sudo: required
services:
  - docker

branches:
  only:
    - master
    - /\d*\.\d*\.\d*/

env:
  global:
    - DOCKER_IMAGE=danielbok/manylinux1_x86_64
    - PLAT=manylinux1_x86_64
    - secure: Heqx5LaxSC7NijXBfSFzG2c2ucMEgbuaBFsEUf4xE+9ldVti1IUOx54HToP70E0K+nLMPyLiILVFTz3bB7LEG+tKoSWq4M1smOQiYO8DQSB/BTCxgkjyl9J6UAFSBxDmbXedv7Iliz4arRTe77Jd5sOdyzF5UtR8+YSVamvisSoblGHg1+OIgtEbVQNvF8N1shyzaSi/OJD3w2ncziplfB9FC66dmLy2Ml7mCiqwzHKq5dNLGMB2PZDDKBXFeWmgrN6sGBvWkQGEn2KDq+m3kJxiAg5bglmjLjD41X/8AOH6002mwV/SsMErrdXl+4f54ByWkBFWE6eUdVF5tEh8hiz266nNBfskRQvNFF0Tm7u7hVozfFi8Xl6PrshjONg5j6jaSMoCrBDB6v5VtE3vdSwXLJ+UgjAr83z1oSqremXIpDsYAUWT4z453Z48OoequqmmyV8ig8elkFirb8hp3qjjVW2tbTsq/n1sL7iY4HXfRV2i+nBvXOBO4t1Ikmo4chDWv8I9mEaGt9gT3t1eHW95S7eG26bc9QZKTaJke3tzOrILQu0G/va509HUPNb3h/F3bVMFF7/P7M6GPeUguKWPIxT4ga+i4t2coNy7mxFkrYZHhsrTmORMSn8gc/BGM+mLDGYnz5rM1LTUMW0dPdJGqrqBR7XsvObs7fjo41g=
    - secure: FkhYYf5zbQnP1PosBmNRQnS+VdULMdFrl1iIj++4PNuTQ0QQm0IaMUwEWZraC6CBYeWVsO3frUGxn9OtaEsm5hrHkE1NySI5FtbVzAjqbDOSovxOZEcV4QNE3lckbcdx5bstzuf1llvCFA3Io4d6stghb3pTe0ida3Yjve7lzeDFCARi6Ajy0B3se2lI0R5AklpnA3vYCicXnznFOfOJD7kMZ1sqz5TU4p2aqbJIRlkIy+pOLm5fjvtAqY88muyUDf8ohdY8OjFzKg6/Rq6rmAkc7iujvPCUKFRgLMYVN2RvNqFfY6IYe03gUGKonosty7mg0X9C6Tp6czAazywDT91ErR3c5+/BBolVk9A3pN+J6wOwYy5/u143+GSU8qYzkKU+2V2z5mhOR67VWQCP/5m94UT8w6otipqKBGZFP5GqOen2u0swZp3/KSMjMOG0plLbeMinvY3UKKpW33IRvsP9v8wsxUo8GaqZi4h0Sfnzz1oInSKI95V8Gfko5BGeJvv6PV5DFg78/zHW56zlXkvQy0DbBOh+2Y4D0am+M3KZWN7mvt0zW6iH5b5PBfs61N03lcxKRSv5iSmntp8C28Wsnc6elzRIGTh9qlZrY3SY/jbKIsmG33gMpBoX4RXyqHS+gkQDpJrRBqXsusqHVlOSGaxVsIfk2mdi1TSvVMI=

before_install:
  - docker pull $DOCKER_IMAGE

install:
  - sudo chmod +x ./build.sh
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/app $DOCKER_IMAGE app/build.sh

stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
    - name: deploy
      before_script:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh -nv
        - chmod +x miniconda3.sh
        - ./miniconda3.sh -b
        - export PATH=/home/travis/miniconda3/bin:$PATH
        - conda config --set always_yes true
        - conda update --all --quiet
        - conda install twine
      script:
        # copy everything to dist folder then upload it
        - rm -rf dist && mkdir -p dist
        - find wheelhouse/ -name "nlopt*-py3-*-manylinux*.whl" -exec cp {} dist/ \;
        - twine upload --verbose --skip-existing -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
