name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop/*
  pull_request:
    branches:
      - master
  release:
    types: [ published ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.3
        env:
          CIBW_BEFORE_BUILD_WINDOWS: choco install swig -y
          CIBW_BEFORE_BUILD_LINUX: yum install swig -y
          CIBW_BEFORE_BUILD_MACOS: brew install swig
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-* cp311-*
          CIBW_SKIP: "*-manylinux_i686 *-musllinux*"
          CIBW_TEST_COMMAND: python extern/nlopt/test/t_python.py