name: Build and push manylinux image

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - image/*
defaults:
  run:
    shell: bash

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: danielbok
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ci
          file: ci/nlopt_manylinux2014_x86_64.Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            danielbok/nlopt_manylinux2014_x86_64:latest
            danielbok/nlopt_manylinux2014_x86_64:${{ steps.current-time.outputs.formattedTime }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
